apiVersion: v1
kind: Service
metadata:
  name: test-nginx
  namespace: test-ns
spec:
  selector:
    app: test-nginx
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32006
